name: Render videos

on:
  push:
    branches:
      - FtC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: FtC

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Setup ffmpeg
        run: |
          sudo apt-get install ffmpeg

      - name: Install ts-node
        run: yarn global add ts-node

      - name: Install dependencies
        run: yarn install

      - name: Install Livepeer React
        run: yarn add @livepeer/react

      - name: Get Video
        run: yarn getVideo
        env:
          LIVEPEER_API_KEY: ${{ secrets.LIVEPEER_API_KEY }}

      - name: Render video
        run: yarn render
        env:
          LIVEPEER_API_KEY: ${{ secrets.LIVEPEER_API_KEY }}

      - name: Upload video
        run: yarn uploadVideo
        env:
          LIVEPEER_API_KEY: ${{ secrets.LIVEPEER_API_KEY }}
